---
settings:
  name: StorageGRID Appliances
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: StorageGRID 應用裝置文件
    url: "/index.html"
  - title: StorageGRID 軟體文件
    url: "/storagegrid-documentation.html"
  - title: 開始使用
    url: "/landing-learn-hdwr/index.html"
    entries:
    - title: 應用裝置的新功能
      url: "/whats-new-appliances.html"
    - title: 瞭解 StorageGRID 應用裝置
      entries:
      - title: SG100與SG1000服務應用裝置
        url: "/installconfig/hardware-description-sg100-and-1000.html"
      - title: SG110 和 SG1100 服務應用裝置
        url: "/installconfig/hardware-description-sg110-and-1100.html"
      - title: SG5700 儲存設備
        url: "/installconfig/hardware-description-sg5700.html"
      - title: SG5800 儲存設備
        url: "/installconfig/hardware-description-sg5800.html"
      - title: SG6000儲存設備
        url: "/installconfig/hardware-description-sg6000.html"
      - title: SG6100 儲存設備
        url: "/installconfig/hardware-description-sg6100.html"
  - section: installconfig
  - title: 維護應用裝置硬體
    url: "/landing-maintain-hdwr/index.html"
    entries:
    - section: commonhardware
    - title: 應用裝置節點複製
      entries:
      - title: 總覽
        pdf-filename: 應用裝置節點複製
        url: "/commonhardware/how-appliance-node-cloning-works.html"
      - title: 應用裝置節點複製的考量與要求
        url: "/commonhardware/considerations-and-requirements-for-appliance-node-cloning.html"
      - title: 複製應用裝置節點
        url: "/commonhardware/appliance-node-cloning-procedure.html"
    - section: sg100-1000
    - section: sg110-1100
    - section: sg5600
    - section: sg5700
    - section: sg5800
    - section: sg6000
    - section: sg6100
  - title: 啟用StorageGRID 功能
    url: "/storagegrid-enable.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
