---
permalink: installconfig/reviewing-appliance-network-connections.html 
sidebar: sidebar 
keywords: network connections, appliance, grid, admin, client, bmc, management 
summary: 安裝StorageGRID 此產品之前、您應該先瞭解哪些網路可以連線至應用裝置。 
---
= 網路類型StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝StorageGRID 此產品之前、您應該先瞭解哪些網路可以連線到應用裝置、以及如何使用每個控制器上的連接埠。StorageGRID 網路需求詳述於 https://docs.netapp.com/us-en/storagegrid-118/network/index.html["網路準則"^]。

請參閱產品說明、以判斷您需要哪些資訊：

* link:gathering-installation-information-sg100-and-sg1000.html["SG100 與 SG1000"]
* link:gathering-installation-information-sg110-and-sg1100.html["SG110 和 SG1100"]
* link:gathering-installation-information-sg5700.html["SG5700"]
* link:gathering-installation-information-sg6000.html["SG6000"]
* link:gathering-installation-information-sg6100.html["SG6100"]


或者、您也可以與 NetApp 專業服務顧問合作、使用 NetApp ConfigBuilder 工具來簡化和自動化組態步驟。請參閱 link:automating-appliance-installation-and-configuration.html["自動化應用裝置的安裝與組態"]。

當您將StorageGRID 某個應用裝置部署為StorageGRID 某個節點的過程中、您可以將其連接至下列網路：

* * Grid Network for StorageGRID Sfor Sfor Sfor *：Grid Network用於所有內部StorageGRID 的資訊流量。它可在網格中的所有節點之間、跨所有站台和子網路提供連線功能。網格網路為必填項目。
* *《StorageGRID Administration Network for S供 參考*：管理網路》是一種封閉網路、用於系統管理與維護。管理網路通常是私有網路、不需要在站台之間進行路由傳送。管理網路為選用網路。
* * StorageGRID Client Network for Sfor Sfor Sfor *用戶端網路是開放式網路、用於存取用戶端應用程式、包括S3和Swift。用戶端網路可提供用戶端傳輸協定存取網格、因此網格網路可以隔離及保護。您可以設定用戶端網路、以便只使用您選擇開啟的連接埠、透過此網路存取應用裝置。用戶端網路為選用項目。
* * SANtricity 管理網路 * （儲存設備選用、 SG6100 不需要）：此網路可讓您存取 SANtricity 系統管理員、讓您監控及管理應用裝置和儲存控制器機櫃中的硬體元件。此管理網路可以與管理員網路StorageGRID 相同、也可以是獨立的管理網路。
* * BMC 管理網路 * （ SG100 、 SG110 、 SG1000 、 SG1100 、 SG6000 、 和 SG6100 ）：此網路可讓您存取 SG100 、 SG1000 、 SG6000 和 SG6100 應用裝置中的主機板管理控制器、讓您監控和管理應用裝置中的硬體元件。此管理網路可以與管理員網路StorageGRID 相同、也可以是獨立的管理網路。
+
如果未連接選用的BMC管理網路、則部分支援與維護程序將更難執行。您可以讓BMC管理網路保持未連線、除非是為了支援目的而需要。




NOTE: 如需 StorageGRID 網路的詳細資訊、請參閱 https://docs.netapp.com/us-en/storagegrid-118/network/storagegrid-network-types.html["網路類型StorageGRID"^]。
