---
permalink: installconfig/verifying-port-level-network-connections.html 
sidebar: sidebar 
keywords: network connections, network connection, network, connection, connectivity, verify, verifying, check, checking, ports, port, port-level, port level, test, testing, udp, Client Network, Admin Network 
summary: 為了確保StorageGRID 不受防火牆阻礙、請確認StorageGRID 《不適用》裝置安裝程式可連線至特定IP位址或位址範圍內的特定TCP連接埠或連接埠集。 
---
= 驗證連接埠層級的網路連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保StorageGRID 不受防火牆阻礙、請確認StorageGRID 《不適用》裝置安裝程式可連線至特定IP位址或位址範圍內的特定TCP連接埠或連接埠集。

.關於這項工作
您可以使用StorageGRID 《解決方案安裝程式》中提供的連接埠清單、測試應用裝置與Grid Network中其他節點之間的連線能力。

此外、您也可以在管理網路和用戶端網路上、以及在諸如外部NFS或DNS伺服器所使用的udp連接埠上測試連線能力。如需這些連接埠的清單，請參閱 https://docs.netapp.com/us-en/storagegrid/network/network-port-reference.html["網路連接埠參考"^]。


NOTE: 連接埠連線表中列出的網格網路連接埠僅適用於 StorageGRID 11.7 版或更新版本。若要驗證每種節點類型的連接埠是否正確、請務必參閱StorageGRID 您的版本的《網路指南》。

.步驟
. 從「SectionAppliance安裝程式」中、按一下StorageGRID 「*組態網路*>*連接埠連線測試（nmap）*」。
+
隨即顯示「連接埠連線測試」頁面。

+
連接埠連線表列出需要網格網路上TCP連線的節點類型。針對每種節點類型、表格會列出您的應用裝置應可存取的Grid Network連接埠。

+
您可以測試表格中所列應用裝置連接埠與Grid Network中其他節點之間的連線能力。

. 從*網路*下拉式清單中、選取您要測試的網路：*網格*、*管理*或*用戶端*。
. 為該網路上的主機指定以空格分隔的清單或 IPv4 位址範圍。
. 輸入TCP連接埠號碼、以逗號分隔的連接埠清單、或連接埠範圍。
. 按一下「*測試連線能力*」。
+
** 如果所選連接埠層級網路連線有效，則會以綠色橫幅顯示「連接埠連線測試通過」訊息。 nmap 命令輸出列在橫幅下方。無法存取的主機不會出現在 nmap 指令輸出中。
** 如果與遠端主機建立了端口級網路連接，但主機未監聽一個或多個選定的端口，則會在黃色橫幅中顯示「端口連接測試失敗」訊息。 nmap 命令輸出列在橫幅下方。無法存取的主機不會出現在 nmap 指令輸出中。
+
主機未接聽的任何遠端連接埠都會顯示「Closed」（已關閉）狀態。 例如、當您嘗試連線的節點處於預先安裝狀態、StorageGRID 且該節點上尚未執行「更新服務」時、您可能會看到這個黃色橫幅。

** 如果無法為一個或多個選定連接埠建立連接埠層級網路連接，則會以紅色橫幅顯示「連接埠連接測試失敗」訊息。 nmap 命令輸出列在橫幅下方。無法存取的主機不會出現在 nmap 指令輸出中。
+
紅色橫幅表示TCP連線嘗試連接遠端主機上的連接埠、但未將任何內容傳回傳送者。當沒有傳回回應時、連接埠的狀態為「已篩選」、可能會被防火牆封鎖。

+

NOTE: 也會列出「Closed」（已關閉）的連接埠。




