---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: 如果E5700SG控制器無法正常運作或故障、您可能需要更換它。 
---
= 更換StorageGRID E5700SG 運算控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果E5700SG控制器無法正常運作或故障、您可能需要更換它。

.開始之前
* 您的更換控制器的零件編號與您要更換的控制器相同。
* 您已下載E系列指示、以更換故障的E5700控制器。
+

NOTE: 有關具體步驟的更多詳細信息，請參閱 E 系列說明。請勿使用它們來更換StorageGRID設備中的控制器，因為步驟不同。例如，E5700 控制器的 E 系列說明描述如何從故障控制器中取出電池和主機介面卡 (HIC) 並將其安裝到替換控制器中。這些步驟不適用於StorageGRID E5700SG 控制器。

* 您可以使用標籤來識別連接至控制器的每條纜線。


.關於這項工作
更換控制器後，您將無法存取設備儲存節點。如果 E5700SG 控制器功能正常，您可以在此程序開始時執行受控關機。


NOTE: 如果您在安裝StorageGRID 完此程序之前更換控制器、可能StorageGRID 無法在完成此程序後立即存取《產品安裝程式（到此程序）」。雖然您可以從與應用裝置位於同一子網路上的其他主機存取 StorageGRID 應用裝置安裝程式、但您無法從其他子網路上的主機存取。此情況應在15分鐘內自行解決（當原始控制器的任何ARP快取項目逾時時）、或者您可以從本機路由器或閘道手動清除任何舊的ARP快取項目、以立即清除此狀況。

.步驟
. 關閉 E5700SG 控制器。
+
.. 登入網格節點：
+
... 輸入下列命令： `ssh admin@_grid_node_IP_`
... 輸入中所列的密碼 `Passwords.txt` 檔案：
... 輸入下列命令以切換至root： `su -`
... 輸入中所列的密碼 `Passwords.txt` 檔案：
+
當您以root登入時、提示會從變更 `$` 至 `#`。





. 關閉 E5700SG 控制器：*`shutdown -h now` *
. 如果StorageGRID 連接至控制器的整個DHCP網路使用DHCP伺服器：
+
.. 記下更換控制器上連接埠的MAC位址（位於控制器的標籤上）。
.. 請網路管理員更新原始控制器的IP位址設定、以反映更換控制器的MAC位址。
+

CAUTION: 在將替換控制器插入裝置之前，必須確保原始控制器的 IP 位址已更新。否則，控制器啟動時將取得新的 DHCP IP 位址，並且可能無法重新連線到StorageGRID。此步驟適用於連接到控制器的所有StorageGRID網路。



. 從應用裝置中取出控制器：
+
.. 放置於防靜電腕帶上或採取其他防靜電預防措施。
.. 標示纜線、然後拔下纜線和SFP。
+

NOTE: 為避免效能降低、請勿扭轉、摺疊、夾緊或踏上纜線。

.. 擠壓CAM握把上的栓鎖直到釋放為止、然後打開右側的CAM握把、即可從產品中釋放控制器。
.. 使用兩隻手和CAM握把、將控制器滑出產品。
+

CAUTION: 請務必用兩隻手支撐控制器的重量。



. 將替換控制器安裝到設備中。
+
.. 翻轉控制器、使可拆式護蓋面朝下。
.. 將CAM握把放在開啟位置、將控制器完全滑入產品。
.. 將CAM握把往左移動、將控制器鎖定到位。
.. 更換纜線和SFP。


. 控制器成功開機後、七段顯示器應顯示下列項目：
+
** E2800 系列控制器：
+
最終狀態是 `99`。

** E5700SG 控制器：
+
最終狀態是 `HA`。



. 設備重新加入電網後，確認設備儲存節點出現在電網管理器中，且沒有警報。


更換零件後、請將故障零件歸還給NetApp、如套件隨附的RMA指示所述。請參閱 https://mysupport.netapp.com/site/info/rma["零件退貨擴大機；更換"^] 頁面以取得更多資訊。

.相關資訊
https://docs.netapp.com/us-en/e-series-family/index.html["NetApp E 系列文件"^]
