---
permalink: sg5800/replace-controller-5800sg.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 更換 SG5800 控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 SG5800 控制器無法正常運作或故障、您可能需要更換它。

.開始之前
* 您的更換控制器的零件編號與您要更換的控制器相同。
* 您可以使用標籤來識別連接至控制器的每條纜線。


.關於這項工作
當您更換控制器時、將無法存取應用裝置儲存節點。如果 SG5800 控制器運作正常、您可以在本程序開始時執行控制關機。


NOTE: 如果您在安裝StorageGRID 完此程序之前更換控制器、可能StorageGRID 無法在完成此程序後立即存取《產品安裝程式（到此程序）」。雖然您可以從與應用裝置位於同一子網路的其他主機存取 StorageGRID 應用裝置安裝程式、但您無法從其他子網路上的主機存取。此情況應在15分鐘內自行解決（當原始控制器的任何ARP快取項目逾時時）、或者您可以從本機路由器或閘道手動清除任何舊的ARP快取項目、以立即清除此狀況。

.步驟
. 關閉 SG5800 控制器。
+
.. 登入網格節點：
+
... 輸入下列命令： `ssh admin@grid_node_IP`
... 輸入中所列的密碼 `Passwords.txt` 檔案：
... 輸入下列命令以切換至root： `su -`
... 輸入中所列的密碼 `Passwords.txt` 檔案：
+
當您以root登入時、提示會從變更 `$` 至 `#`。



.. 關閉 SG5800 控制器：
+
*`shutdown -h now`*

.. 等待快取記憶體中的任何資料寫入磁碟機。
+
當需要將快取資料寫入磁碟機時、 E4000 控制器背面的綠色快取作用中 LED 會亮起。您必須等待此LED燈關閉。



. 關閉電源。
+
.. 從 SANtricity 系統管理員首頁、選取檢視進行中的作業。
.. 確認所有作業均已完成。
.. 關閉產品上的兩個電源開關。
.. 等待所有LED關閉。


. 如果StorageGRID 連接至控制器的整個DHCP網路使用DHCP伺服器：
+
.. 記下更換控制器上連接埠的MAC位址（位於控制器的標籤上）。
.. 請網路管理員更新原始控制器的IP位址設定、以反映更換控制器的MAC位址。
+

NOTE: 您必須先確認原始控制器的IP位址已更新、才能將電源供應給更換的控制器。否則、當控制器開機時、就會取得新的DHCP IP位址、而且可能無法重新連線StorageGRID 到故障。此步驟適用於StorageGRID 連接至控制器的所有環節網路。



. 從應用裝置中取出控制器：
+
.. 放置於防靜電腕帶上或採取其他防靜電預防措施。
.. 標示纜線、然後拔下纜線和SFP。
+

NOTE: 為避免效能降低、請勿在纜線上扭轉、摺疊、夾住或踩踏。
擠壓CAM握把上的栓鎖直到釋放為止、然後打開右側的CAM握把、即可從產品中釋放控制器。

.. 使用兩隻手和CAM握把、將控制器滑出產品。
+

NOTE: 請務必用兩隻手支撐控制器的重量。



. 將替換控制器安裝到設備中。
+
.. 翻轉控制器、使可拆式護蓋面朝下。
.. 將CAM握把放在開啟位置、將控制器完全滑入產品。
.. 將CAM握把往左移動、將控制器鎖定到位。
.. 更換纜線。


. 開啟產品電源、並監控控制器 LED 。
. 確認應用裝置儲存節點出現在Grid Manager中、且未顯示任何警示。


更換零件後、請將故障零件歸還給NetApp、如套件隨附的RMA指示所述。請參閱 https://mysupport.netapp.com/site/info/rma["零件退貨擴大機；更換"] 頁面以取得更多資訊。
