---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: 在複製應用裝置節點之前、您必須先瞭解考量事項與需求。 
---
= 應用裝置節點複製的考量與要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在複製應用裝置節點之前、您必須先瞭解考量事項與需求。


TIP: 網關節點的節點克隆功能已停用。若要取代網關節點，請先將其退役，然後執行擴充功能以新增新的裝置網關節點。網關節點的退役和擴展過程比儲存節點快得多。



== 更換應用裝置的硬體需求

確保更換設備符合下列條件：

* 來源節點（正在更換的應用裝置）和目標（新）應用裝置必須是相同類型的應用裝置：
+
** 您只能將管理節點設備複製到新的服務設備。
** 您只能將儲存節點應用裝置複製到新的儲存應用裝置。


* 對於管理節點設備，來源節點設備和目標設備不需要是相同的設備型號；但是，更改設備型號可能需要更換電纜或 SFP 模組。
+
例如、您可以用SG100來取代SG1000節點應用裝置、或是用SG1000應用裝置來取代SG100應用裝置。

* 對於 Storage Node 應用裝置、來源節點應用裝置和目標應用裝置不需要是相同類型的應用裝置；不過：
+
** 目標應用裝置的儲存容量必須大於來源應用裝置。
+
例如、您可以使用 SG6000 應用裝置來更換 SG5700 節點應用裝置。

** 目標應用裝置的物件儲存磁碟區數量必須等於或大於來源應用裝置。
+
例如，您不能用 SGF6112 設備（12 個物件儲存磁碟區）取代 SG6000 節點裝置（16 個物件儲存磁碟區）。





請聯絡StorageGRID 您的銷售代表、以協助您選擇相容的替換設備、以便在StorageGRID 安裝時複製特定的應用裝置節點。



== 準備複製應用裝置節點

在複製應用裝置節點之前、您必須具備下列資訊：

* 從網路管理員處取得網格網路的暫用IP位址、以便在初始安裝期間與目標應用裝置搭配使用。如果來源節點屬於管理網路或用戶端網路、請取得這些網路的暫用IP位址。
+
臨時 IP 位址通常與複製的來源節點應用裝置位於相同的子網路上、而且在複製完成後不需要。來源和目標應用裝置必須同時連線StorageGRID 至您的支援區的主要管理節點、才能建立複製連線。

* 判斷要用於複製資料傳輸流量的網路、以提供最佳的資料傳輸效能、而不會降低StorageGRID 網路效能或資料可用度。
+

NOTE: 使用1-GbE管理網路進行複製資料傳輸、會導致複製速度變慢。

* 決定是否將在目標裝置上使用金鑰管理伺服器 (KMS) 進行節點加密，以便您可以在複製之前在初始目標裝置安裝期間啟用節點加密。您可以檢查來源設備節點上是否啟用了節點加密，例如link:../installconfig/optional-enabling-node-encryption.html["啟用節點加密"]。
+
來源節點和目標設備可以有不同的節點加密設置，但有以下例外。對於以下設備，不支援從未加密節點來源到節點加密目標的節點克隆：

+
** 不含節點加密的 SGF6112 節點設備到有節點加密的 SGF6112 設備
** 不含節點加密的 SG1100 節點設備到有節點加密的 SG1100 設備
** 不含節點加密的 SG110 節點設備到有節點加密的 SG110 設備


+
在資料傳輸過程中以及目標節點重新啟動並加入電網時，資料解密和加密會自動執行。

* 判斷目標應用裝置上的RAID模式是否應從預設設定變更、以便在複製前於初始目標應用裝置安裝期間指定此資訊。您可以在Grid Manager的「*節點*」頁面上、檢視來源應用裝置節點目前RAID模式的相關資訊。選取應用裝置的 * 硬體 * 標籤。
+
來源節點和目標應用裝置可以有不同的RAID設定。

* 規劃足夠的時間來完成節點複製程序。可能需要數天的時間、才能將資料從運作中的儲存節點傳輸到目標應用裝置。排定複製時間、將對貴企業的影響降至最低。
* 一次只能複製一個應用裝置節點。複製可防止您StorageGRID 同時執行其他的還原維護功能。
* 複製應用裝置節點之後、您可以使用返回預先安裝狀態的來源應用裝置做為目標、來複製另一個相容的節點應用裝置。

