---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: 您可以在StorageGRID 更新設計或增強功能的應用裝置上、複製到位的應用裝置節點。複製會將現有節點的所有資訊傳輸至新應用裝置、提供易於執行的硬體升級程序、並提供取代設備的停用和擴充替代方案。 
---
= 應用裝置節點複製：概觀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在StorageGRID 更新設計或增強功能的應用裝置上、複製到位的應用裝置節點。複製會將現有節點的所有資訊傳輸至新應用裝置、提供易於執行的硬體升級程序、並提供取代設備的停用和擴充替代方案。

應用裝置節點複製功能可讓您輕鬆地將網格中現有的應用裝置節點（來源）更換為同StorageGRID 一個邏輯版本的相容應用裝置（目標）。此程序會將所有資料傳輸至新應用裝置、並將其置於服務狀態、以更換舊應用裝置節點、並使舊應用裝置保持預先安裝狀態。



== 為何要複製應用裝置節點？

如果需要：

* 更換即將停產的設備。
* 升級現有節點、以善用改良的應用裝置技術。
* 增加網格儲存容量、而不需變更StorageGRID 您的一套系統中的儲存節點數量。
* 改善儲存效率、例如將RAID模式從DDA-8變更為DDA-16、或變更為RAID-6。
* 有效實作節點加密、以允許使用外部金鑰管理伺服器（KMS）。




== 使用哪StorageGRID 一個呢？

複製可透過StorageGRID 任一項功能、將資料從來源節點直接傳輸至目標應用裝置。網格網路通常會使用、但如果來源應用裝置連線至這些網路、您也可以使用管理網路或用戶端網路。選擇用於複製流量的網路、以提供最佳資料傳輸效能、而不會降低StorageGRID 網路效能或資料可用度。

安裝替換應用裝置時、您必須指定暫時性的IP位址、以便StorageGRID 進行鏈接和資料傳輸。由於替換應用裝置將與它所取代的應用裝置節點屬於同一個網路、因此您必須在替換應用裝置上為每個網路指定暫用 IP 位址。



== 哪些資訊未複製？

在複製期間、下列應用裝置組態不會傳輸至替換應用裝置。您必須在更換設備的初始設定期間進行設定。

* BMC 介面
* 網路連結
* 節點加密狀態
* 系統管理程式（適用於儲存節點）SANtricity
* RAID模式（適用於儲存節點）




== 哪些問題會妨礙複製？

如果在複製時遇到下列任何問題、複製程序會停止、並產生錯誤訊息：

* 網路組態錯誤
* 來源設備與目標設備之間缺乏連線能力
* 來源與目標應用裝置不相容
* 儲存節點是容量不足的替換應用裝置


您必須解決複製的每個問題才能繼續。



== 目標應用裝置相容性

更換設備必須與要更換的來源節點類型相同、而且兩者都必須屬於同一個邏輯StorageGRID 版的站台。

複製前、請先檢閱一般的複製考量、以及每種應用裝置類型的特定複製資訊和限制。



=== 一般服務應用裝置複製考量

* 更換服務應用裝置的型號可能與它所更換的管理節點或閘道節點不同。
* 服務應用裝置有不同的網路連接器。變更應用裝置類型可能需要更換纜線或SFP模組。




=== 一般儲存設備複製考量

* 更換儲存設備的容量必須大於正在更換的儲存節點。
+
** 如果目標儲存設備的磁碟機數量與來源節點相同、則目標應用裝置中的磁碟機容量必須更大（以 TB 為單位）。
** 如果您計畫在目標節點上使用與來源節點相同的 RAID 模式、 或是儲存效率較低的 RAID 模式（例如從 RAID 6 切換至 DDP ）、目標應用裝置中的磁碟機必須比來源應用裝置中的磁碟機大（ TB ）。
** 一般儲存設備複製考量的例外情況包括：
+
*** 如果目標儲存設備中安裝的標準磁碟機數量少於來源節點中的磁碟機數量、因為安裝了固態磁碟機（ SSD ）、則目標應用裝置中標準磁碟機的整體儲存容量（ TB ） 必須超過來源儲存節點中所有磁碟機的總功能磁碟機容量。
+
例如、將具有 60 個磁碟機的 SG5760 來源儲存節點設備複製到具有 58 個標準磁碟機的 SG6060 目標應用裝置時、在複製前、應先在 SG6060 目標應用裝置中安裝較大的磁碟機、以維持儲存容量。（目標應用裝置中包含 SSD 的兩個磁碟機插槽不包含在應用裝置的總儲存容量中。）

+
不過、如果 60 個磁碟機的 SG5760 來源節點應用裝置已設定 SANtricity Dynamic Disk Pools DDS-8 （ DDP ）、則使用 DDS-16 設定 58 個磁碟機的相同大小磁碟機 SG6060 目標應用裝置、可能會因為 SG6060 應用裝置的儲存效率提升而成為有效的複製目標。

+
您可以在Grid Manager的「*節點*」頁面上、檢視來源應用裝置節點目前RAID模式的相關資訊。選取應用裝置的「*儲存設備*」索引標籤。

*** 目標儲存設備中的磁碟區數量必須大於或等於來源節點中的磁碟區數量。即使目標應用裝置的容量大於來源節點、您也無法將具有 16 個物件儲存區（ rangedb ）的來源節點複製到具有 12 個物件儲存區的目標儲存應用裝置。除了 SFF6112 儲存設備只有 12 個物件儲存磁碟區之外、大部分的儲存設備都有 16 個物件儲存磁碟區。








=== SG100 應用裝置複製資訊與限制

您可以將 SG100 來源節點應用裝置複製到 SG110 、 SG1000 或 SG1100 服務目標應用裝置。將 SG100 複製到 SG1000 或 SG1100 服務目標應用裝置、可讓管理節點或閘道節點擁有更大的功能。



=== SG110 應用裝置複製資訊與限制

您可以將 SG110 來源節點應用裝置複製到 SG1100 服務應用裝置目標、讓管理節點或閘道節點擁有更大的功能。



=== SG1000 應用裝置複製資訊與限制

您可以將 SG1000 來源節點應用裝置複製到 SG100 、 SG110 或 SG1100 服務目標應用裝置。

* 將 SG1000 複製到 SG100 或 SG110 服務目標應用裝置、可讓您重新部署 SG1000 、以滿足要求更嚴苛的應用程式。
* 以SG100服務目標應用裝置取代SG1000來源節點應用裝置、可將網路連接埠的最大速度從100-GbE降低至25-GbE。




=== SG1100 應用裝置複製資訊與限制

您可以將 SG1100 來源節點應用裝置複製到 SG110 服務目標應用裝置。

* 將 SG1100 複製到 SG110 服務目標應用裝置、可讓您重新部署 SG1100 、以滿足要求更嚴苛的應用程式。例如、如果SG1100來源節點應用裝置做為管理節點、而您想要將其用作專屬的負載平衡節點。
* 以 SG110 服務目標應用裝置取代 SG1100 來源節點應用裝置、可將網路連接埠的最大速度從 100-GbE 降低到 25-GbE 。




=== SG5712 設備複製資訊與限制

您可以將使用 DDP 設定的 SG5712 來源節點應用裝置複製到 SG5812 儲存目標應用裝置。



=== SG5760 應用裝置複製資訊與限制

* 您可以將使用 DDP16 設定的 SG5760 來源節點應用裝置複製到使用 DDP16 設定的 SG5860 儲存目標應用裝置。
* 使用 DDP _ 設定的 SG5760 來源節點應用裝置無法複製到使用 DDP 設定的 SG5860 儲存目標應用裝置。
* 使用 DDP 或 DDS-16 _ 設定的 SG5760 來源節點應用裝置無法複製到具有相符 RAID 模式的 SG6160 儲存目標應用裝置。




=== SG5812 設備複製資訊與限制

您可以成功複製 SG5812 應用裝置作為來源或目標。



=== SG5860 應用裝置複製資訊與限制

您可以成功複製 SG5860 應用裝置作為來源或目標、但有一些限制（列於應用裝置的複製資訊和每個來源的限制中）。



=== SG6060 應用裝置複製資訊與限制

* 您可以將使用 DDP 或 DDP16 設定的 SG6060 來源節點應用裝置複製到具有相符 RAID 模式的 SG5860 儲存目標應用裝置。
* 如果磁碟機大小和 RAID 模式相同、您可以將 SG6060 來源節點應用裝置複製到 SG6160 儲存目標應用裝置、而無需任何擴充架。
* 即使擴充機櫃數量、磁碟機大小和 RAID 模式相同、也無法將具有任何擴充機櫃數量的 SG6060 來源節點應用裝置複製到 SG6160 儲存目標應用裝置。




=== SG6160 應用裝置複製資訊與限制

您可以成功複製 SG6160 應用裝置作為來源或目標、但有一些限制（列於應用裝置的複製資訊和每個來源的限制中）。
